<a href="https://colab.research.google.com/github/Ayushsan1/Pytorch-Implementation-and-Foundation/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Fundamentals (Initials) of PyTorch
Resourecs: https://github.com/mrdbourke/pytorch-deep-learning

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


#### Introduction to tensors - a way to represent representing numericals (multi-dimensional data)

PyTorch Tensors: https://pytorch.org/docs/stable/tensors.html


In [ ]:
##Scalar
scalar=torch.scalar_tensor(7)
scalar
#scalar.ndim

tensor(7.)

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
#Matrix
Matrix=torch.tensor([[7,8],
                   [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(Matrix.ndim)
print(Matrix.shape)

2
torch.Size([2, 2])


In [ ]:
Matrix[0]

tensor([7, 8])

In [ ]:
#Tensor's
Tensor=torch.tensor([[[[1,2,3],
                       [3,6,9],
                       [2,4,5],
                       [6, 4, 5]]]])
Tensor

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5],
          [6, 4, 5]]]])

In [ ]:
print(Tensor.ndim)
print(Tensor.shape) # this shows we got 1 3X3 matrix here

4
torch.Size([1, 1, 4, 3])


##Random Tensors :
Random Tensors are imp bcs the way many neural networks learn is that they start
with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
#Create a Random tensor of size (3,4)
random_tensor=torch.rand(4,3) #generates random tensors of the size specified
random_tensor

tensor([[0.3671, 0.1642, 0.6704],
        [0.3891, 0.1017, 0.0311],
        [0.5322, 0.6294, 0.6767],
        [0.8946, 0.3663, 0.9748]])

In [ ]:
random_tensor.ndim

2

###Create a random tensor with similar shape to an image tensor
######This creates a tensor for an example of image of particular specified dimensional of the image as image are also represent in form of tensors in computing language

In [ ]:
#this is basically to understand how images we click we offcourse use to have some 2d (hieght and width) acn be represented as tensors
image_size_tensor = torch.rand(size=(3,224,224)) #height, width, colour_channel
print(image_size_tensor.shape)
print(image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


####Zeroes and Ones (0 & 1) tensors

In [ ]:
#tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype) # this tells the data type of the tensors numbers

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


#### Creating a Range of Tensors and Tensors-like

In [ ]:
arch=torch.arange(0,10) # we use arange bcs range is deprecated
print(arch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
torch.arange(start=0, end=200, step=66) # this gives the range from where start, end and the gap they can take to continue reaching the end

tensor([  0,  66, 132, 198])

In [ ]:
zeros_like = torch.zeros_like(arch)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor([[ 7,  8],
        [ 9, 10]])


#### Tensors Data Types

Different Data types are used for precision purpose which means "how many bits are used to store each parameter or weight" as higher precision as higher bit/param... as higher precision provide great accuracy but require more memory.
**In Simple terms it is the detail you want in data at cost of computing**

In [ ]:
#Float 32 tensor
F32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
print(F32_tensor.dtype) # it show float32 as bcs its by default

#Float16
F16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, #tensor data type
                          device='cpu', #the device your tensor is on
                          requires_grad=False) #require_grad means to calculate Gradient
print(F16_tensor.dtype)

torch.float32
torch.float16


In [ ]:
#multiplying two different data type of tensors
F16_tensor*F32_tensor #smth like multiplication of matrix

tensor([ 9., 36., 81.])

###Fetching Info about Tensors

In [ ]:
#Information ( base attributes) of tensor
exm_tensor = torch.rand(3,4)
print(exm_tensor)
print(f"Datatype of tensor: {exm_tensor.dtype}")
print(f"Shape of tensor: {exm_tensor.shape}")
print(f"Device tensor is on: {exm_tensor.device}")
#

tensor([[0.9415, 0.8523, 0.3256, 0.8133],
        [0.9522, 0.5292, 0.5365, 0.6724],
        [0.1451, 0.4048, 0.5635, 0.0565]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#### Manipulating Tensors
Tensor Operation Includes as :
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Matrix Multiplication

In [ ]:
tensor1 = Tensor + 10
print(tensor1)
tensor2 = Tensor * 10
print(tensor2)
tensor3 = Tensor - 10
print(tensor3)
tensor4 = Tensor / 10
print(tensor4)
# Pytorch also its built in function for operation like "torch.mul" & "torch.add" like torch.add(Tensor, 10)

tensor([[[[11, 12, 13],
          [13, 16, 19],
          [12, 14, 15],
          [16, 14, 15]]]])
tensor([[[[10, 20, 30],
          [30, 60, 90],
          [20, 40, 50],
          [60, 40, 50]]]])
tensor([[[[-9, -8, -7],
          [-7, -4, -1],
          [-8, -6, -5],
          [-4, -6, -5]]]])
tensor([[[[0.1000, 0.2000, 0.3000],
          [0.3000, 0.6000, 0.9000],
          [0.2000, 0.4000, 0.5000],
          [0.6000, 0.4000, 0.5000]]]])


###Matrix Multiplication
 There are 2 two ways to multiply :
 1. Element wise multiplication
 2. Matrix Multiplication (dot product)

In [ ]:
Tensor_new = torch.tensor([[[1,2,3],
                           [4,5,6],
                            [7,8,9]]])

In [ ]:
#Element wise
print(Tensor_new, "*", Tensor_new)
print(f"Equals: {Tensor_new * Tensor_new}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) * tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Equals: tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])


In [ ]:
#Matrix Multiplication
torch.matmul(Tensor_new, Tensor_new) #this predefined function is way more faster than manually implementing the matrix multiplication

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])