<a href="https://colab.research.google.com/github/Ayushsan1/Pytorch-Implementation-and-Foundation/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Fundamentals (Initials) of PyTorch
Resourecs: https://github.com/mrdbourke/pytorch-deep-learning

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


#### Introduction to tensors - a way to represent representing numericals (multi-dimensional data)

PyTorch Tensors: https://pytorch.org/docs/stable/tensors.html


In [3]:
##Scalar
scalar=torch.scalar_tensor(7)
scalar
#scalar.ndim

tensor(7.)

In [4]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [6]:
#Matrix
Matrix=torch.tensor([[7,8],
                   [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
print(Matrix.ndim)
print(Matrix.shape)

2
torch.Size([2, 2])


In [8]:
Matrix[0]

tensor([7, 8])

In [9]:
#Tensor's
Tensor=torch.tensor([[[[1,2,3],
                       [3,6,9],
                       [2,4,5],
                       [6, 4, 5]]]])
Tensor

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5],
          [6, 4, 5]]]])

In [10]:
print(Tensor.ndim)
print(Tensor.shape) # this shows we got 1 3X3 matrix here

4
torch.Size([1, 1, 4, 3])


##Random Tensors :
Random Tensors are imp bcs the way many neural networks learn is that they start
with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [11]:
#Create a Random tensor of size (3,4)
random_tensor=torch.rand(4,3) #generates random tensors of the size specified
random_tensor

tensor([[0.7887, 0.0944, 0.7593],
        [0.4111, 0.0717, 0.0207],
        [0.6911, 0.6204, 0.1467],
        [0.8184, 0.7414, 0.2429]])

In [12]:
random_tensor.ndim

2

###Create a random tensor with similar shape to an image tensor
######This creates a tensor for an example of image of particular specified dimensional of the image as image are also represent in form of tensors in computing language

In [13]:
#this is basically to understand how images we click we offcourse use to have some 2d (hieght and width) acn be represented as tensors
image_size_tensor = torch.rand(size=(3,224,224)) #height, width, colour_channel
print(image_size_tensor.shape)
print(image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


####Zeroes and Ones (0 & 1) tensors

In [14]:
#tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
#tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype) # this tells the data type of the tensors numbers

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


#### Creating a Range of Tensors and Tensors-like

In [16]:
arch=torch.arange(0,10) # we use arange bcs range is deprecated
print(arch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
torch.arange(start=0, end=200, step=66) # this gives the range from where start, end and the gap they can take to continue reaching the end

tensor([  0,  66, 132, 198])

In [18]:
zeros_like = torch.zeros_like(arch)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensors Data Types

Different Data types are used for precision purpose which means "how many bits are used to store each parameter or weight" as higher precision as higher bit/param... as higher precision provide great accuracy but require more memory.
**In Simple terms it is the detail you want in data at cost of computing**

In [19]:
#Float 32 tensor
F32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
print(F32_tensor.dtype) # it show float32 as bcs its by default

#Float16
F16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, #tensor data type
                          device='cpu', #the device your tensor is on
                          requires_grad=False) #require_grad means to calculate Gradient
print(F16_tensor.dtype)

torch.float32
torch.float16


In [20]:
#multiplying two different data type of tensors
F16_tensor*F32_tensor #smth like multiplication of matrix

tensor([ 9., 36., 81.])

###Fetching Info about Tensors

In [21]:
#Information ( base attributes) of tensor
exm_tensor = torch.rand(3,4)
print(exm_tensor)
print(f"Datatype of tensor: {exm_tensor.dtype}")
print(f"Shape of tensor: {exm_tensor.shape}")
print(f"Device tensor is on: {exm_tensor.device}")
#

tensor([[0.3781, 0.6649, 0.3103, 0.0960],
        [0.1892, 0.7695, 0.5446, 0.6375],
        [0.8351, 0.4615, 0.3833, 0.0968]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#### Manipulating Tensors
Tensor Operation Includes as :
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Matrix Multiplication

In [22]:
tensor1 = Tensor + 10
print(tensor1)
tensor2 = Tensor * 10
print(tensor2)
tensor3 = Tensor - 10
print(tensor3)
tensor4 = Tensor / 10
print(tensor4)
# Pytorch also its built in function for operation like "torch.mul" & "torch.add" like torch.add(Tensor, 10)

tensor([[[[11, 12, 13],
          [13, 16, 19],
          [12, 14, 15],
          [16, 14, 15]]]])
tensor([[[[10, 20, 30],
          [30, 60, 90],
          [20, 40, 50],
          [60, 40, 50]]]])
tensor([[[[-9, -8, -7],
          [-7, -4, -1],
          [-8, -6, -5],
          [-4, -6, -5]]]])
tensor([[[[0.1000, 0.2000, 0.3000],
          [0.3000, 0.6000, 0.9000],
          [0.2000, 0.4000, 0.5000],
          [0.6000, 0.4000, 0.5000]]]])


###Matrix Multiplication
 There are 2 two ways to multiply :
 1. Element wise multiplication
 2. Matrix Multiplication (dot product)

 There are common error in Deep Learning:
 There are two main rule that performing matrix multiplication needs to satisfy:-
 1. The **Inner Dimension** must match:
 * '(3,2) @ (3,2)' won't work
 * '(2,3) @ (3,2)' will work
 * '(3,2) @ (2,3)' will work
 2. The resulting matrix has the shape of the **outer dimenson**:
 * '(2,3) @ (3,2)' --> (2,2)
 * '(3,2) @ (2,3)' --> (3,3)

In [23]:
Tensor_new = torch.tensor([[[1,2,3],
                           [4,5,6],
                            [7,8,9]]])

In [24]:
#Element wise
print(Tensor_new, "*", Tensor_new)
print(f"Equals: {Tensor_new * Tensor_new}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) * tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Equals: tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])


In [25]:
#Matrix Multiplication
%time
torch.matmul(Tensor_new, Tensor_new) #this predefined function is way more faster than manually implementing the matrix multiplication

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.87 µs


tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

###Discussing the common error in DL as Shape Error

In [32]:
#Shapes for Matrix Multiplication
tensor_A = torch.tensor ([[1,2],
                           [3,4],
                           [5,6]])
tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [35]:
#to fix the above shape error we can do transpose one tensor to make inner dimension match and work
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [36]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [38]:
# Full detailed visualisation of Matrix Multiplication and Shape Error correction
print(f"Original shapes: Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.shape}")
print(f"New shapes: Tensor_A = {tensor_A.shape} ), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
New shapes: Tensor_A = torch.Size([3, 2]) ), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Tensor Aggregration
1. Min
2. Max
3. Mean
4. Sum... etc (arg.max, arg.min)

In [40]:
x = torch.arange (0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [43]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [51]:
#Find the mean
#now 'torch.mean(x)' would not work as now the x as dtype as int64 or long, but it should be either float or complex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the Positional Min and Max

In [53]:
x.argmin() # returns the index position where the min values occurs

tensor(0)

In [57]:
print(x.argmax())  #finds the index of tensor with max value
x[9] #checking actual max value at that index

tensor(9)


tensor(90)

### Reshaping, Stacking, Squeezing, and Unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target torch.tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
import torch
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [81]:
#Add an extra dimension
x_reshaped = x.reshape(1,9) #we have to take care that we can only add dimension only as the shape of tensor
x_reshaped, x_reshaped.shape #now it has become added one dimension into it

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [74]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [77]:
#changing z changes x ( bcs view of a tensor shares the same memory as the original)
z[:, 0] = 5
print(z)
print(x) # here we can see that change in z, made also change in x as they are both at same memory as view.

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])


In [80]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [87]:
#Squeeze - removes ingle dimensions from the target tensors
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [94]:
#Unsqueeze - add single dimension to target tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
#

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [98]:
#Permute - rearrange the dimensions of target tensor in specified order
x_original = torch.rand(size=(224,224,3))

 #permute the original tensor to rearrange the dimensions (axis)
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Select data from tensors)
Indexing with Pytorch is similar to indexing in Numpy

In [99]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [100]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
print(x[0,2]) # gives the tensor result of 0th index 2nd index value tensor
print(x[0][0][0])
x[0][1][1]

tensor([7, 8, 9])
tensor(1)


tensor(5)

In [117]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd dimensions
x[:,:,1]

tensor([[2, 5, 8]])

In [118]:
#index on x to return 9
x[0,2,2]

tensor(9)

##PyTorch Tensors and Numpy

* Data in NUmpy to want in PyTorch Tensor --> 'torch.from_numpy(ndarray)
* PyTorch tensor --> torch.tensor.numpy()

In [124]:
import torch
import numpy as np

array =np.arange(1, 8)
tensor = torch.from_numpy(array) # from converting numpy --> pytorch, pytorch reflect numpy default dtype
print(array)
print(tensor)
#when we will change numpy array, this will not change tensor and vice versa for tensor

[1 2 3 4 5 6 7]
tensor([1, 2, 3, 4, 5, 6, 7])


In [125]:
#Tensor to Nparray
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor)
print(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


### Reproducibility in PyTorch : trying to make random out of random

In short how a neural network learns:
'start with random number --> tensor operations--> update random number to try and make them better representation
of the data --> again --> again...'

to reduce the randomness in NN and PyTorch comes the concept of a *random see*
Essentially what the random seed does is flavour the randomness.

In [127]:
#create 2 random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # checks if both tensors are equal

tensor([[0.4102, 0.2707, 0.2959, 0.8526],
        [0.3139, 0.7410, 0.0416, 0.5355],
        [0.9534, 0.5506, 0.0561, 0.1330]])
tensor([[0.9705, 0.4994, 0.4428, 0.7424],
        [0.0713, 0.4902, 0.5387, 0.2925],
        [0.2347, 0.0316, 0.6510, 0.7458]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [131]:
from numpy._core.multiarray import RAISE
#Lets make some random but reproducible tensors
#set the random seed for controlled randomness
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch object on GPU and making faster computations
as
GPU = faster computation on number, thanks to CUDA + Pytorch working behind

As PyTorch is made to run gpus , the best way to practice device agnostic code: https://docs.pytorch.org/docs/2.13/notes/cuda.html

In [1]:
!nvidia-smi

Wed Jul 29 09:51:57 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
## 2. Check for GPU access in PyTorch
import torch
torch.cuda.is_available()

True

In [3]:
device ='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
#Count the no. of GPU's
torch.cuda.device_count()

1

### Putting Tensor (or Models) on GPU
The reason for putting tensor on GPU is to have faster results.

In [7]:
tensor = torch.tensor([1,2,3]) #by default on CPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [8]:
#Move Tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) #the device variable we created using torch.cuda.is_available
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
#moving tensor numpy to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu

<function Tensor.numpy>